package ldif.local

import datasources.dump.DumpExecutor
import runtime._
import impl.{BlockingQuadQueue, EntityQueue, QuadQueue}
import ldif.modules.silk.SilkModule
import ldif.datasources.dump.{DumpModule, DumpConfig}
import ldif.modules.silk.local.SilkLocalExecutor
import de.fuberlin.wiwiss.ldif.local.EntityBuilderExecutor
import de.fuberlin.wiwiss.ldif.{EntityBuilderModule, EntityBuilderConfig}
import java.io.{FileWriter, File}
import de.fuberlin.wiwiss.r2r._
import ldif.modules.r2r.local.R2RLocalExecutor
import ldif.modules.r2r._
import ldif.entity.EntityDescription


object Main
{
  def main(args : Array[String])
  {
    var debug = false
    if(args.length<1) {
      println("No configuration file given.")
      System.exit(1)
    }
    else if(args.length>=2 && args(0)=="--debug")
      debug = true

    //val configUrl = getClass.getClassLoader.getResource("ldif/local/example/test2/config.xml")
    //val configFile = new File(configUrl.toString.stripPrefix("file:"))
    val configFile = new File(args(args.length-1))
    runIntegrationFlow(configFile, debug)
  }

  def runIntegrationFlow(configFile: File, debugMode: Boolean) {
    stopWatch.getTimeSpanInSeconds
    val config = LdifConfiguration.load(configFile)
    println("Time needed to load config file: " + stopWatch.getTimeSpanInSeconds + "s")

    val quadReaders = loadDump(config.sourceDir)

    //if(debug==true)
    //  writeDebugOutput("dump", config.outputFile, dumpReader)

    val r2rReader = mapQuads(config.mappingFile, quadReaders)
    println("Time needed to map data: " + stopWatch.getTimeSpanInSeconds + "s")
    println("Number of triples after mapping the input dump: " + r2rReader.size)

    val clonedR2rReader = cloneQuadQueue(r2rReader)

    if(debugMode==true)
      writeDebugOutput("r2r", config.outputFile, r2rReader)

    val linkReader = generateLinks(config.linkSpecDir, r2rReader)
    println("Time needed to link data: " + stopWatch.getTimeSpanInSeconds + "s")
    println("Number of links generated by silk: " + linkReader.size)

    if(debugMode==true)
      writeDebugOutput("silk", config.outputFile, linkReader)

    val integratedReader = URITranslator.translateQuads(clonedR2rReader, linkReader)

    println("Time needed to translate URIs: " + stopWatch.getTimeSpanInSeconds + "s")

    //OutputValidator.compare(cloneQuadQueue(integratedReader),new File(configFile.getParent+"/../results/all-mes.nt"))

    writeOutput(config.outputFile, integratedReader)
  }

  def runIntegrationFlow(configFile: File) {
    runIntegrationFlow(configFile, false)
  }

  /**
   * Loads the dump files.
   */
  def loadDump(dumpDir : File) : Seq[QuadReader] =
  {
    val dumpModule = new DumpModule(new DumpConfig(dumpDir.listFiles.map(_.getCanonicalPath)))
    val dumpExecutor = new DumpExecutor

    val quadQueues = for (i <- 1 to dumpModule.tasks.size) yield new BlockingQuadQueue

    for((dumpTask, writer) <- dumpModule.tasks.toList zip quadQueues){
      runInBackground
        {
          dumpExecutor.execute(dumpTask, null, writer)
        }
    }
    quadQueues.toSeq
  }

  /**
   * Transforms the Quads
   */
  def mapQuads(mappingFile: File, readers: Seq[QuadReader]) : QuadReader = {
    val repository = new Repository(new FileOrURISource(mappingFile.getAbsolutePath))
    val executor = new R2RLocalExecutor
    val config = new R2RConfig(repository)
    val module = new R2RModule(config)

    val entityDescriptions = for(task <- module.tasks) yield task.mapping.entityDescription
    val entityReaders = buildEntities(readers, entityDescriptions.toSeq)
    println("Time needed to load dump and build entities for mapping phase: " + stopWatch.getTimeSpanInSeconds + "s")
    //println("Number of triples after loading the dump: " + (quadReaders.foldLeft(0)(_ + _.totalSize)))

    val outputQueue = new QuadQueue

    //runInBackground
    {
      for((r2rTask, reader) <- module.tasks.toList zip entityReaders)
        executor.execute(r2rTask, Seq(reader), outputQueue)
    }

    outputQueue
  }

  /**
   * Generates links.
   */
  def generateLinks(linkSpecDir : File, reader : QuadReader) : QuadReader =
  {
    val silkModule = SilkModule.load(linkSpecDir)
    val silkExecutor = new SilkLocalExecutor

    val entityDescriptions = silkModule.tasks.toIndexedSeq.map(silkExecutor.input).flatMap{ case StaticEntityFormat(ed) => ed }
    val entityReaders = buildEntities(Seq(reader), entityDescriptions)
    println("Time needed to build entities for linking phase: " + stopWatch.getTimeSpanInSeconds + "s")

    val outputQueue = new QuadQueue

    //runInBackground
    {
      for((silkTask, readers) <- silkModule.tasks.toList zip entityReaders.grouped(2).toList)
      {
        silkExecutor.execute(silkTask, readers, outputQueue)
      }
    }

    outputQueue
  }

  /**
   * Build Entities.
   */
  def buildEntities(readers : Seq[QuadReader], entityDescriptions : Seq[EntityDescription]) : Seq[EntityReader] =
  {
    val entityQueues = entityDescriptions.map(new EntityQueue(_))

    //runInBackground
    {
      val entityBuilderConfig = new EntityBuilderConfig(entityDescriptions.toIndexedSeq)
      val entityBuilderModule = new EntityBuilderModule(entityBuilderConfig)
      val entityBuilderTask = entityBuilderModule.tasks.head
      val entityBuilderExecutor = new EntityBuilderExecutor

      entityBuilderExecutor.execute(entityBuilderTask, readers, entityQueues)
    }

    entityQueues
  }

  /**
   * Evaluates an expression in the background.
   */
  private def runInBackground(function : => Unit) {
    val thread = new Thread {
      override def run() {
        function
      }
    }
    thread.start()
  }

  //TODO we don't have an output module yet...
  def writeOutput(outputFile : File, reader : QuadReader)    {
    val writer = new FileWriter(outputFile)
    var count = 0

    while(!reader.isEmpty) {
      writer.write(reader.read().toNQuadFormat + " .\n")
      count += 1
    }

    writer.close()
    println(count + " Quads written")
  }

  def writeDebugOutput(phase: String, outputFile: File, reader: QuadReader) {
    if(reader.isInstanceOf[QuadQueue] && !reader.isInstanceOf[BlockingQuadQueue]) {
      val newOutputFile = new File(outputFile.getAbsolutePath + "." + phase)
      val clonedReader = cloneQuadQueue(reader)
      writeOutput(newOutputFile, clonedReader)
    }
  }

  // Only clone QuadQueue implementation of QuadReader
  def cloneQuadQueue(queue: QuadReader) = {
    if(queue.isInstanceOf[QuadQueue])
      queue.asInstanceOf[QuadQueue].clone
    else
      null
  }
}

object stopWatch {
  private var lastTime = System.currentTimeMillis

  def getTimeSpanInSeconds(): Double = {
    val newTime = System.currentTimeMillis
    val span = newTime - lastTime
    lastTime = newTime
    span / 1000.0
  }
}